services:
  - type: web
    name: gifts-web-client-prod
    rootDir: client
    runtime: static
    staticPublishPath: .output/public
    buildCommand: yarn; yarn generate
    envVars:
      - fromGroup: gifts-envs-prod
      - key: NODE_VERSION
        value: 20.10.0
    buildFilter:
      paths:
      - client/**
      ignoredPaths:
      - scripts/**
      - README.md
      - graphql.config.yml
      - .gitignore
  - type: web
    name: gifts-web-server-prod
    rootDir: server
    plan: starter
    env: python
    buildCommand: poetry install --only main && ./manage.py collectstatic --no-input
    preDeployCommand: ./manage.py migrate --no-input
    startCommand: python -m daphne gifts.asgi:application --bind=0.0.0.0
    healthCheckPath: /healthcheck/
    envVars:
      - fromGroup: gifts-envs-prod
      - key: DATABASE_URL
        fromDatabase:
          name: gifts-db-prod
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.12.1
    disk:
      name: media
      mountPath: /var/lib/media
      sizeGB: 1
    buildFilter:
      paths:
      - server/**
      ignoredPaths:
      - scripts/**
      - README.md
      - graphql.config.yml
      - .gitignore

databases:
  - name: gifts-db-prod
    user: gifts
    databaseName: gifts
    ipAllowList: []
    plan: free

envVarGroups:
  - name: gifts-envs-prod
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ENV
        value: prod
      - key: MEDIA_ROOT
        value: /var/lib/media
      - key: POSTMARK_SERVER_TOKEN
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: SERVER_URL
        sync: false
      - key: CLIENT_URL
        sync: false
