services:
  - type: web
    name: gifts-web-client-prod
    rootDir: client
    plan: free
    env: node
    buildCommand: yarn; yarn build
    startCommand: yarn start
    envVars:
      - fromGroup: gifts-envs-prod
  - type: web
    name: gifts-web-server-prod
    rootDir: server
    plan: starter
    env: python
    buildCommand: poetry install --only main && ./manage.py collectstatic --no-input
    preDeployCommand: ./manage.py migrate --no-input
    startCommand: python -m daphne gifts.asgi:application --bind=0.0.0.0
    healthCheckPath: /healthcheck/
    envVars:
      - fromGroup: gifts-envs-prod
      - key: DATABASE_URL
        fromDatabase:
          name: gifts-db-prod
          property: connectionString
    disk:
      name: media
      mountPath: ./media
      sizeGB: 1

databases:
  - name: gifts-db-prod
    user: gifts
    databaseName: gifts
    ipAllowList: []
    plan: free

envVarGroups:
  - name: gifts-envs-prod
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ENV
        value: prod
      - key: PYTHON_VERSION
        value: 3.12.1
      - key: SERVER_URL
        sync: false
      - key: CLIENT_URL
        sync: false
